In [24]:
import tensorflow as tf

# Create a 10x10 grid filled with zeros
grid = tf.zeros((10, 10), dtype=tf.float32)

# Specify the indices where ones should be placed
ones_indices = [(2, 3), (4, 7), (6, 1), (7, 5), (8, 0), (8, 9), (9, 2), (9, 4), (9, 6), (9, 8)]

# Create an array of ones with the same length as ones_indices
ones = tf.ones(len(ones_indices), dtype=tf.float32)
grid_test = tf.tensor_scatter_nd_update(grid, ones_indices, ones)

grid2 = tf.zeros((10, 10), dtype=tf.float32)
ones = tf.ones(len(ones_indices), dtype=tf.float32)
grid_pred = tf.tensor_scatter_nd_update(grid2, ones_indices, ones)

# Print the resulting grid
print(grid_test)
print(grid_pred)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 1. 0. 1. 0. 1. 0.]], shape=(10, 10), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 1. 0. 1. 0. 1. 0.]], shape=(10, 10), dtype=float32)


In [29]:
def accuracy_00(y_true, y_pred):

    # Count the number of correct 1s
    # correct_ones = tf.reduce_sum(tf.cast(tf.logical_and(tf.equal(y_true_flat, 1), tf.equal(tf.round(y_pred_flat), 1)), dtype=tf.float32))
    
    # Flatten the tensor
    y_true_flat = tf.reshape(y_true, [-1])
    y_pred_flat = tf.reshape(y_pred, [-1])

    # Count the total number of ones
    correct_ones = tf.reduce_sum(tf.cast(tf.logical_and(tf.greater(y_true_flat, 0.0), tf.greater(y_pred_flat, 0.0)), dtype=tf.float32))
    total_ones = tf.reduce_sum(tf.cast(tf.equal(y_true_flat, 1.0), dtype=tf.float32))

    print(correct_ones)
    print(total_ones)

    # Print the result
    return (correct_ones / total_ones)

In [30]:
accuracy_00(grid_test, grid_pred)

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor(10.0, shape=(), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=1.0>